#!/usr/bin/env bash
# bootstrap.sh — interactive prompts to generate .env from .env.example.
#
# Run this once, BEFORE setup.sh. It only writes a local .env file in the
# repo root. It does not touch ~/.claude.
#
# Usage:
#   bash install/bootstrap.sh

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$REPO_ROOT/.env"
ENV_EXAMPLE="$REPO_ROOT/.env.example"

if [[ ! -f "$ENV_EXAMPLE" ]]; then
  echo "ERROR: .env.example not found at $ENV_EXAMPLE" >&2
  exit 1
fi

if [[ -f "$ENV_FILE" ]]; then
  echo "WARNING: .env already exists at $ENV_FILE"
  read -r -p "Overwrite? [y/N]: " ans
  case "$ans" in
    y|Y) ;;
    *) echo "Aborted."; exit 0 ;;
  esac
fi

echo
echo "claude-brainlab bootstrap — fill in your environment."
echo "Press Enter to accept the [default] in brackets."
echo

ask() {
  local var="$1" prompt="$2" default="${3:-}" reply
  if [[ -n "$default" ]]; then
    read -r -p "$prompt [$default]: " reply
    reply="${reply:-$default}"
  else
    read -r -p "$prompt: " reply
  fi
  printf -v "$var" '%s' "$reply"
}

ask_secret() {
  local var="$1" prompt="$2" reply
  read -r -s -p "$prompt (input hidden, Enter to skip): " reply
  echo
  printf -v "$var" '%s' "$reply"
}

# ── Obsidian ──
ask VAULT_NAME       "Obsidian vault folder name"        "my-vault"
default_vault_path="$HOME/Library/Mobile Documents/iCloud~md~obsidian/Documents/$VAULT_NAME"
ask OBSIDIAN_VAULT   "Full path to vault root"           "$default_vault_path"

# ── Project roots ──
ask PAPERS_ROOT      "Papers folder (research papers)"   "$HOME/Papers"
ask PROJECTS_ROOT    "Projects folder (code projects)"   "$HOME/Projects"
ask STAFF_ROOT       "Staff folder (people work)"        "$HOME/Staff"

# ── Python ──
default_py="$(command -v python3 || echo python3)"
ask PYTHON_BIN       "Python interpreter (absolute path recommended)" "$default_py"

# ── Zotero ──
echo
echo "Zotero (optional — leave blank to skip Zotero MCP):"
ask_secret ZOTERO_API_KEY    "ZOTERO_API_KEY"
ask        ZOTERO_LIBRARY_ID "ZOTERO_LIBRARY_ID (numeric)" ""
ask        UNPAYWALL_EMAIL   "UNPAYWALL_EMAIL"             "you@example.com"

# ── User identity ──
ask USER_EMAIL "Your contact email" "$UNPAYWALL_EMAIL"

cat > "$ENV_FILE" <<EOF
# Generated by install/bootstrap.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
VAULT_NAME=$VAULT_NAME
OBSIDIAN_VAULT=$OBSIDIAN_VAULT
PAPERS_ROOT=$PAPERS_ROOT
PROJECTS_ROOT=$PROJECTS_ROOT
STAFF_ROOT=$STAFF_ROOT
PYTHON_BIN=$PYTHON_BIN
ZOTERO_API_KEY=$ZOTERO_API_KEY
ZOTERO_LIBRARY_ID=$ZOTERO_LIBRARY_ID
UNPAYWALL_EMAIL=$UNPAYWALL_EMAIL
USER_EMAIL=$USER_EMAIL
EOF

chmod 600 "$ENV_FILE"

echo
echo "✓ Wrote $ENV_FILE (chmod 600)"
echo "Next step: bash install/setup.sh"
