# setup-windows.ps1 -- native Windows installer for claude-brainlab.
#
# No WSL, no rsync required. Works in Windows PowerShell 5.1 and PowerShell 7.
# NOTE: keep this file ASCII-only -- PS 5.1 reads BOM-less files as ANSI and
# multi-byte punctuation (em dash, smart quotes) corrupts the parse.
#
#   powershell -ExecutionPolicy Bypass -File install\setup-windows.ps1
#
# What it does:
#   1. Creates .env interactively if missing (Windows-native paths).
#   2. Copies skills/ commands/ agents/ hooks/ scripts/ rules/ into ~/.claude
#      (existing files are backed up to ~/.claude/.claude-brainlab-backups).
#   3. Expands ${VAR} placeholders and renders settings.json (hooks, statusline).
#   4. Writes ~/.claude/obsidian-projects.json from your project roots.
#   5. Registers MemPalace + Zotero MCP servers via `claude mcp add -s user`.
#      This writes ~/.claude.json -- the ONLY config both the Claude Code CLI
#      and the desktop app actually read for MCP servers. (mcpServers inside
#      ~/.claude/settings.json is ignored by both -- do not put servers there.)
#
# Switches:
#   -SkipMcp   install files only, skip MCP registration
#   -McpOnly   only (re-)register MCP servers, skip file install
#
# Full guide: docs/WINDOWS.md

param(
    [switch]$SkipMcp,
    [switch]$McpOnly
)

$ErrorActionPreference = 'Stop'
$RepoRoot   = Split-Path $PSScriptRoot -Parent
# CLAUDE_HOME env var overrides the default (parity with the bash scripts).
$ClaudeHome = $env:CLAUDE_HOME
if ([string]::IsNullOrWhiteSpace($ClaudeHome)) {
    $ClaudeHome = Join-Path $env:USERPROFILE '.claude'
}
$EnvFile    = Join-Path $RepoRoot '.env'
$Ts         = Get-Date -Format 'yyyyMMdd-HHmmss'
$BackupDir  = Join-Path $ClaudeHome ".claude-brainlab-backups\$Ts"
$LocalBin   = Join-Path $env:USERPROFILE '.local\bin'

# Hooks and helper scripts print emoji; stop cp1251 consoles from crashing them.
$env:PYTHONIOENCODING = 'utf-8'

function Write-Step($msg) { Write-Host "  $msg" }

# --- 1. .env: load or create -------------------------------------------------
function New-DotEnv {
    Write-Host "No .env found - let's create one (Enter accepts the default)."
    $docs = ($env:USERPROFILE -replace '\\', '/') + '/Documents'
    $ask = {
        param($prompt, $default)
        $v = Read-Host "$prompt [$default]"
        if ([string]::IsNullOrWhiteSpace($v)) { return $default }
        return $v
    }
    $vals = [ordered]@{
        VAULT_NAME        = & $ask 'Obsidian vault name'          'my-vault'
        OBSIDIAN_VAULT    = & $ask 'Obsidian vault full path'     "$docs/my-vault"
        PAPERS_ROOT       = & $ask 'Papers projects root'         "$docs/Papers"
        PROJECTS_ROOT     = & $ask 'Projects root'                "$docs/Projects"
        STAFF_ROOT        = & $ask 'Staff projects root'          "$docs/Staff"
        PYTHON_BIN        = & $ask 'Python interpreter'           'C:/Windows/py.exe'
        ZOTERO_API_KEY    = & $ask 'Zotero API key (optional)'    ''
        ZOTERO_LIBRARY_ID = & $ask 'Zotero library ID (optional)' ''
        UNPAYWALL_EMAIL   = & $ask 'Email for Unpaywall API'      'you@example.com'
        USER_EMAIL        = & $ask 'Your email'                   'you@example.com'
    }
    $lines = @("# Generated by install/setup-windows.ps1 on $(Get-Date -Format s)")
    foreach ($k in $vals.Keys) { $lines += ('{0}="{1}"' -f $k, $vals[$k]) }
    $lines -join "`n" | Out-File -FilePath $EnvFile -Encoding utf8
    Write-Step "wrote $EnvFile"
}

if (-not (Test-Path $EnvFile)) { New-DotEnv }

# Parse KEY="value" / KEY=value lines and export as env vars for child tools.
$DotEnv = @{}
foreach ($line in Get-Content $EnvFile -Encoding UTF8) {
    if ($line -match '^\s*#' -or $line -notmatch '=') { continue }
    $k, $v = $line -split '=', 2
    $v = $v.Trim().Trim('"')
    $DotEnv[$k.Trim()] = $v
    Set-Item -Path "env:$($k.Trim())" -Value $v
}
# ${HOME} in templates must render as the Windows home, forward slashes.
$env:HOME = $env:USERPROFILE -replace '\\', '/'

$Py = $DotEnv['PYTHON_BIN']
if ([string]::IsNullOrWhiteSpace($Py)) { $Py = 'py' }
$Render = Join-Path $PSScriptRoot 'render_config.py'

# --- 2-4. File install -------------------------------------------------------
if (-not $McpOnly) {
    Write-Host "-> Installing claude-brainlab into $ClaudeHome"
    New-Item -ItemType Directory -Force -Path $ClaudeHome | Out-Null

    $components = @('skills', 'commands', 'agents', 'hooks', 'scripts', 'rules')
    foreach ($c in $components) {
        $src = Join-Path $RepoRoot $c
        $dst = Join-Path $ClaudeHome $c
        if (-not (Test-Path $src)) { Write-Step "[skip] $c (not in repo)"; continue }
        if (Test-Path $dst) {
            New-Item -ItemType Directory -Force -Path $BackupDir | Out-Null
            Copy-Item $dst (Join-Path $BackupDir $c) -Recurse -Force
        }
        New-Item -ItemType Directory -Force -Path $dst | Out-Null
        Copy-Item (Join-Path $src '*') -Destination $dst -Recurse -Force
        Write-Step "copied $c"
    }

    # CLAUDE.md: never clobber the user's own global instructions.
    $userMd = Join-Path $ClaudeHome 'CLAUDE.md'
    if (Test-Path $userMd) {
        Copy-Item (Join-Path $RepoRoot 'CLAUDE.md') (Join-Path $ClaudeHome 'CLAUDE.brainlab.md') -Force
        Write-Step 'CLAUDE.md -> CLAUDE.brainlab.md (sidecar; yours kept)'
    } else {
        Copy-Item (Join-Path $RepoRoot 'CLAUDE.md') $userMd
        Write-Step 'CLAUDE.md (new)'
    }

    & $Py $Render expand --claude-home $ClaudeHome
    if ($LASTEXITCODE -ne 0) { throw 'placeholder expansion failed' }

    $settingsDst = Join-Path $ClaudeHome 'settings.json'
    if (Test-Path $settingsDst) {
        New-Item -ItemType Directory -Force -Path $BackupDir | Out-Null
        Copy-Item $settingsDst (Join-Path $BackupDir 'settings.json') -Force
    }
    & $Py $Render render-settings `
        --template (Join-Path $RepoRoot 'settings.json.template') `
        --output $settingsDst --strip-mcp-servers
    if ($LASTEXITCODE -ne 0) { throw 'settings.json render failed' }

    & $Py $Render projects-json --output (Join-Path $ClaudeHome 'obsidian-projects.json')
    if ($LASTEXITCODE -ne 0) { throw 'obsidian-projects.json write failed' }

    # Manifest: what we installed, used by uninstall-windows.ps1 to know which
    # components were newly created (vs merely updated) and can be removed.
    $manifestLines = @("# claude-brainlab install manifest - $Ts")
    foreach ($c in $components) { $manifestLines += (Join-Path $ClaudeHome $c) }
    $manifestLines += (Join-Path $ClaudeHome 'settings.json')
    $manifestLines += (Join-Path $ClaudeHome 'CLAUDE.brainlab.md')
    $manifestLines -join "`n" | Out-File -FilePath (Join-Path $ClaudeHome '.claude-brainlab-manifest.txt') -Encoding utf8

    if (Test-Path $BackupDir) { Write-Step "backups: $BackupDir" }
}

# --- 5. MCP registration (the part that actually wires up memory/Zotero) -----
if (-not $SkipMcp) {
    Write-Host '-> Registering MCP servers (user scope, ~/.claude.json)'

    if (-not (Get-Command claude -ErrorAction SilentlyContinue)) {
        Write-Step 'claude CLI not found - installing @anthropic-ai/claude-code via npm'
        npm install -g '@anthropic-ai/claude-code'
        if ($LASTEXITCODE -ne 0) { throw 'npm install of claude CLI failed' }
    }

    $mempalace = Join-Path $LocalBin 'mempalace-mcp.exe'
    $zotero    = Join-Path $LocalBin 'zotero-mcp.exe'

    # NOTE: '--' must be quoted -- PS 5.1 strips a bare `--` from native
    # command arguments, and without it the variadic -e flags swallow the path.
    if (Test-Path $mempalace) {
        cmd /c "claude mcp remove mempalace -s user >nul 2>&1"
        claude mcp add mempalace -s user '--' ($mempalace -replace '\\', '/')
        if ($LASTEXITCODE -ne 0) { throw 'claude mcp add mempalace failed' }
    } else {
        Write-Warning "mempalace-mcp.exe not found in $LocalBin. Install it first:  uv tool install mempalace"
    }

    if (Test-Path $zotero) {
        $email = $DotEnv['UNPAYWALL_EMAIL']
        cmd /c "claude mcp remove zotero -s user >nul 2>&1"
        claude mcp add zotero -s user `
            -e ZOTERO_LOCAL=true `
            -e ZOTERO_LIBRARY_TYPE=user `
            -e "UNPAYWALL_EMAIL=$email" `
            -e UNSAFE_OPERATIONS=all `
            '--' ($zotero -replace '\\', '/') serve
        if ($LASTEXITCODE -ne 0) { throw 'claude mcp add zotero failed' }
    } else {
        Write-Warning "zotero-mcp.exe not found in $LocalBin. Install it first:  uv tool install zotero-mcp-server"
    }

    Write-Host ''
    Write-Host '-> Health check (zotero needs the Zotero app running):'
    claude mcp list
}

Write-Host ''
Write-Host 'Done. Restart Claude Code (or start a new session) to pick everything up.'
Write-Host 'Verify inside a session: ask for "mempalace_status" and "zotero_get_collections".'
